# Generated by Django 2.1.4 on 2019-01-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('license_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GenericQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('patient_id', models.CharField(max_length=300)),
                ('diagnosis', models.CharField(max_length=300)),
                ('doctor', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=100)),
                ('parent_fullname', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=300)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartSuperHero.Patient')),
            ],
        ),
    ]
