# Generated by Django 2.1.5 on 2019-01-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSuperHero', '0002_auto_20190120_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericQuestion',
        ),
    ]
